[WIP] add_pft_tracking
scilus/nf-scil pull request #11
Opened 2023-11-10 19:33 UTC by Manonedde

First update of the PFT Tracking module. 

To do: 
- Update the test_data (I've just set the paths while waiting for the guidelines, no data provided).
- Test the module.

@AlexVCaron

2023-11-10 20:24 UTC, Manonedde commented
Module test with fake data. 
Test pass.

2023-11-15 02:10 UTC, gagnonanthony commented on modules/nf-scil/tracking/pfttracking/main.nf
> +    def pft_nbr_seeds = task.ext.pft_nbr_seeds ? "-- "  + task.ext.pft_nbr_seeds : ""
```suggestion
    def pft_nbr_seeds = task.ext.pft_nbr_seeds ? ""  +  task.ext.pft_nbr_seeds : ""
```
This provides the number of seeds for $pft_seeding_type, no? If this is the case, there shouldn't be the "-- ".

2023-11-15 02:14 UTC, gagnonanthony commented on modules/nf-scil/tracking/pfttracking/main.nf
> +    def pft_seeding_mask = task.ext.pft_seeding_mask_type ? "--"  + task.ext.pft_seeding_mask_type : ""
Delete this since it is not used in the script.

2023-11-15 02:19 UTC, gagnonanthony commented on tests/modules/nf-scil/tracking/pfttracking/nextflow.config
> +        ext.pft_seeding_mask_type = "wm"
Same as the last comment.

2023-11-15 02:20 UTC, gagnonanthony requested changes
Minor changes, otherwise LGTM ! :beer: 😄

2023-11-15 02:48 UTC, gagnonanthony commented on modules/nf-scil/tracking/pfttracking/main.nf
> +    def args = task.ext.args ?: ''
Not needed since there is not args in the stub section

2023-11-16 19:20 UTC, gagnonanthony approved these changes

2023-11-17 03:55 UTC, AlexVCaron requested changes
Nice work 😁 A few things and I merge !

2023-11-17 03:55 UTC, AlexVCaron commented on modules/nf-scil/tracking/pfttracking/meta.yml
> +  - trk:
Should be `config`

2023-11-17 03:55 UTC, AlexVCaron commented on tests/modules/nf-scil/tracking/pfttracking/test.yml
> +- name: tracking pfttracking test_tracking_pfttracking
You can remove this file from the PR.

2023-11-17 03:55 UTC, AlexVCaron commented on tests/config/test_data.config
> +                exclude = "${params.test_data_base}/main/.test_data/preproc/b0_mask.nii.gz"
Replace with explicative filenames for now (fodf.nii.gz, ...).

2023-11-22 18:33 UTC, AlexVCaron approved these changes
This is ready to go ! Once you know you're in sync with the `main`, remove the WIP status and I merge.

2023-11-22 18:51 UTC, merged