[WIP] add option T1 for N4 module
scilus/nf-scil pull request #111
Opened 2024-03-25 18:47 UTC by ThoumyreStanislas

modification of the N4 module to process the T1 image and renaming of inputs and outputs to make them more generic.

2024-03-26 19:49 UTC, arnaudbore approved these changes
LGTM

2024-03-26 20:04 UTC, gagnonanthony approved these changes
Looks good!

2024-03-27 12:57 UTC, AlexVCaron requested changes
Very nice improvment ! A few comments, then GTG !

2024-03-27 12:57 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
> +      description: Nifti image file mask to use as reference
Maybe `for the reference` is a better wording here ?

2024-03-27 12:57 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
>        description: DWI image N4 corrected
```suggestion
       description: N4 corrected image
```

2024-03-27 12:57 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/main.nf
> +            -o [${prefix}__ref_n4.nii.gz, bias_field_ref.nii.gz]\
This gets included in the `image` output of the module. Either change the name here or specify the glob for the output further.

I am not against outputting this, but it should be done in another optional output channel.

2024-03-27 12:57 UTC, AlexVCaron commented on tests/modules/nf-scil/preproc/n4/test.yml
> +    - path: output/preproc/test__ref_n4.nii.gz
This is the extra output that could pose problem

2024-03-27 13:42 UTC, AlexVCaron approved these changes

2024-03-27 14:06 UTC, merged