[Subworkflow][WIP] T1 preprocessing workflow.
scilus/nf-scil pull request #112
Opened 2024-03-25 20:17 UTC by ThoumyreStanislas

creation of sub-workflows for T1 image pre-processing. the workflow goes from denoising to cropping. for the moment, the N4 module is out of the loop, as it's waiting for the T1 option on the module. tests haven't yet run on this workflow, as I'm still having some difficulty understanding how to define the input data for the workflow.I'm also waiting for answers to @gagnonanthony questions about local test execution.

2024-04-17 21:10 UTC, AlexVCaron requested changes
Very nice ! I have a few comments, mostly rewording in the `meta.yml`. It's going to be merged fast :rocket:

2024-04-17 21:10 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +    to multi-channel head coils).
```suggestion
    Used to normalize the image intensities and reduce biases (e.g. signal loss with distance in
    multi-channel head coils), while preserving contrasts between tissues.
```

2024-04-17 21:10 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +    standard spatial resolution and enables easy registration with corrected DWI images.
```suggestion
    Resamples the T1 to an isotropic spatial resolution. The default is 1mm, a standard in humans which
    usually facilitate registration with corrected DWI images.
```

2024-04-17 21:10 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +    This brain extraction is required for the T1 to DWI Registration.
```suggestion
    Isolates the brain tissue voxels from the remaining image. Also creates a binary brain mask.
    This brain extraction is required for the T1 to DWI Registration.
```

2024-04-17 21:10 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +    Crop the empty planes around the brain to optimize the next processing step.
```suggestion
    Crops the empty planes around the brain to optimize the next processing steps.
```

2024-04-17 21:10 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +  See Tractoflow for more details, https://www.sciencedirect.com/science/article/pii/S105381192030375X?via%3Dihub
```suggestion
  Subworkflow based on Tractoflow : https://www.sciencedirect.com/science/article/pii/S105381192030375X?via%3Dihub
```

2024-04-18 19:33 UTC, gagnonanthony approved these changes
LGTM ! Great job! 🍻

2024-04-19 02:28 UTC, AlexVCaron requested changes
Given the new optional inputs, there is a few things to consider and fix. Let's look at this together tomorrow.

2024-04-19 02:28 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/main.nf
> +        ch_versions = ch_versions.mix(BETCROP_CROPVOLUME.out.versions.first())
Because of the optional input masks, this part becomes way trickier.

First, after resampling, input masks don't fit anymore, they have to be resampled as well. 

Second, if a mask is given, then ANTSBET is not needed.

Third, if a mask is computed with ANTSBET, then it needs to be cropped also.

This all needs to be handled in the `DataFlow` (inside channels). I'll work on a standard way to do it, let's look at it tomorrow.

2024-04-19 02:28 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/main.nf
> +        image_nlmeans   = DENOISING_NLMEANS.out.image     // channel: [ val(meta), [ image ] ]
Put `t1` and `mask` as the final output channels, it'll separate them from the intermediary outputs. And at the top. `mask` is not listed here yet, it's the one from crop.

2024-04-19 02:28 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/meta.yml
> +        Structure: [ val(meta), path(mask) ]
State this is optional, as well as the other masks.

2024-04-19 02:28 UTC, AlexVCaron commented on subworkflows/nf-scil/preproc_t1/tests/main.nf.test
> +nextflow_workflow {
Can you add a test or two with masks ?

2024-04-23 20:11 UTC, AlexVCaron approved these changes

2024-04-23 20:11 UTC, merged