[Subworkflow][WIP] Registration subworkflow.
scilus/nf-scil pull request #115
Opened 2024-03-28 19:49 UTC by gagnonanthony

## Filling your PR description

Registration subworkflow with relevant tests.

2024-04-11 04:06 UTC, AlexVCaron requested changes
Super work ! I'd like more documentation coming with the subworkflows, so it's pretty much all the comments I have :+1:

2024-04-11 13:57 UTC, gagnonanthony commented on subworkflows/nf-scil/registration/meta.yml
I added additional descriptions, tell me if you think it is sufficient!

2024-04-12 15:06 UTC, gagnonanthony commented
For some reasons, it seems like the nf-test setup action is acting out again 🤔 @AlexVCaron

2024-04-12 15:37 UTC, AlexVCaron commented
It should be fixed on the `main`. I needed to modify the fork for PR on the official action, I changed the version we use right now to target the commit before I started that. Sorry for that :stuck_out_tongue:

2024-04-15 17:59 UTC, AlexVCaron commented
@gagnonanthony Sync yourself with the main, the `github workflows` should now be fixed !

2024-04-16 04:30 UTC, AlexVCaron requested changes
Last few comments, then I think it's ready for merge ! :boat:

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/main.nf
> +                                    .map{ [it[0], it[1], it[2], []] }
```suggestion
                                    .map{ it + [[]] }
```

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/meta.yml
> +  It requires as input at least a moving (ch_image) and a reference image (ch_ref) to properly
```suggestion
  It requires as input at least a moving (ch_image) and a reference (ch_ref) image to properly
```

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/meta.yml
> +      module calling AntsRegistration and
```suggestion
      module calling AntsRegistration, with the metric as additional target
```

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/meta.yml
> +  2)  if a metric file is NOT supplied, the subworkflow will use the REGISTRATION_ANTS module calling
```suggestion
  2)  if NO metric file is supplied, the subworkflow will use the REGISTRATION_ANTS module calling
```

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/meta.yml
> +  Typical next steps after this subworkflow would be ANATOMICAL_SEGMENTATION or TRACKING.
Here, I was more talking about what to do with the transformations computed and how to use the `ANTSAPPLYTRANSFORMS` module on images or tractograms.

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/main.nf
> +        transfo_trk   = transfo_trk            // channel: [ val(meta), [ inversewarp, inverseaffine ] ]
This is inverted (or we did something wrong in the registration modules). The correct order should be `[val(meta), [inverseAffine, inverseWarp] ]`

2024-04-16 04:30 UTC, AlexVCaron commented on subworkflows/nf-scil/registration/main.nf
> +            // ** Set up input channel, input are inversed compared to REGISTER_ANATTODWI. ** //
```suggestion
            // ** Set up input channel, input are inverted compared to REGISTER_ANATTODWI. ** //
```

2024-04-16 20:41 UTC, AlexVCaron approved these changes
All good on my end ! AFter you remove WIP and @ThoumyreStanislas passes through the PR, LGTM !

2024-04-18 16:23 UTC, merged