[WIP] Add gibbs module
scilus/nf-scil pull request #14
Opened 2023-11-10 22:50 UTC by arnaudbore

2023-11-16 18:05 UTC, Manonedde requested changes
Minor comments, looks good to me

2023-11-16 18:05 UTC, Manonedde commented on modules/nf-scil/preproc/gibbs/main.nf
> +    def args = task.ext.args ?: ''
you don't have any args, you can delete this line

2023-11-16 18:05 UTC, Manonedde commented on modules/nf-scil/preproc/gibbs/main.nf
> +    def args = task.ext.args ?: ''
Same as previous comment

2023-11-23 18:10 UTC, Manonedde approved these changes

2023-11-23 19:59 UTC, AlexVCaron approved these changes
All good 🚀 LGTM

2023-11-23 20:01 UTC, merged