Migrate tracking modules to scilpy 2.0.0 + nf-test.
scilus/nf-scil pull request #143
Opened 2024-05-01 17:50 UTC by arnaudbore

## Type of improvement

**If submitting a new module or fixing a bug, please use the appropriate template.**

- [ ] Documentation
- [ ] Development tools (e.g. linter, formatter, etc.)
- [ ] Development container
- [x] Global update (please specify)
- [ ] Other (please specify)

## Describe your improvement

Migrate trackings modules to scilpy 2.0.0 + nf-test.

## Checklist before requesting a review

- [x] Ensure the syntax is correct (**EditorConfig** and **Prettier** must pass)
- [x] Run the test suites if your changes affect any module
- [ ] Regenerate the **Poetry** lock file if you have updated the dependencies
- [ ] Ensure the documentation is up-to-date

#79

2024-05-08 12:31 UTC, gagnonanthony requested changes
Great job! 💯  I wrote minor comments (mostly typos), but I wondered if you forgot to migrate the `localtracking` module to `scilpy 2.0`? I can't seem to be able to see the changes, but it might be only me!

2024-05-08 12:31 UTC, gagnonanthony commented on modules/nf-scil/tracking/localtracking/environment.yml
> +  - "scilpy"
Minor comment, but I think everywhere else, `scilpy` is written with a capital S.

2024-05-08 12:31 UTC, gagnonanthony commented on modules/nf-scil/tracking/localtracking/tests/main.nf.test
> +    test("stracking - localtracking - fa") {
Is `stracking` voluntary, or is it a typo?

2024-05-09 15:24 UTC, AlexVCaron requested changes

2024-05-09 15:24 UTC, AlexVCaron commented on modules/nf-scil/tracking/localtracking/main.nf
> +<<<<<<< HEAD
Merge error

2024-05-10 15:24 UTC, merged