[Module] Compute/resample centroids module.
scilus/nf-scil pull request #154
Opened 2024-05-21 18:34 UTC by gagnonanthony

## Describe your changes

Add a compute/resample centroids for the bundles module. If only bundles are provided, centroids are computed. If centroids are provided, they are resampled.

## List test packages used by your module

- `bundles.zip`
- `filtering.zip`

## Checklist before requesting a review

- Create the tool:
  - [x] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [x] Add test data locally for tests with the fork repository
  - [x] Generate the test infrastructure and _md5sum_ for all outputs
- Ensure the syntax is correct :
  - [x] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [x] Lint everything. Ensure your variables have good names.

2024-05-21 19:55 UTC, AlexVCaron requested changes
Excellent job ! However, I prefer a different module for tractogram resampling and use it for centroids resampling in the future subworkflow, instead of putting it all in one module. Implemented the way it is here, it doesn't save us anything at execution.

2024-05-21 19:55 UTC, AlexVCaron commented on modules/nf-scil/bundle/centroid/main.nf
This should be split in two different modules : one for computing the centroids on bundles, the other for `TRACTOGRAM_RESAMPLE`.

2024-05-22 14:38 UTC, arnaudbore approved these changes
GTG (almost)

2024-05-22 14:38 UTC, arnaudbore commented on modules/nf-scil/bundle/centroid/main.nf
> +        tuple val(meta), path("*_centroid_{*}.{trk,tck}")   , emit: centroids
you can use tck if a reference has been provided. Use only trk.

2024-05-22 19:32 UTC, merged