[Module] Label Map module.
scilus/nf-scil pull request #158
Opened 2024-05-22 16:17 UTC by gagnonanthony

## Describe your changes

Add label map module.

## List test packages used by your module

- `tractometry.zip`

## Checklist before requesting a review

- Create the tool:
  - [x] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [x] Add test data locally for tests with the fork repository
  - [x] Generate the test infrastructure and _md5sum_ for all outputs
- Ensure the syntax is correct :
  - [x] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [x] Lint everything. Ensure your variables have good names.

2024-05-22 16:25 UTC, AlexVCaron requested changes
One minor comment, everything else is #1 !

2024-05-22 16:25 UTC, AlexVCaron commented on modules/nf-scil/bundle/labelmap/main.nf
> +        if [[ -f \${centroids[index]} ]]; then
Remove the `if`, I would prefer the process to fail if the centroids list doesn't have the same size.

2024-05-22 20:42 UTC, arnaudbore reviewed
couple of comments

2024-05-22 20:42 UTC, arnaudbore commented on modules/nf-scil/bundle/labelmap/main.nf
> +
extra lign

2024-05-22 20:42 UTC, arnaudbore commented on modules/nf-scil/bundle/labelmap/tests/nextflow.config
> +    withName: "BUNDLE_LABELMAP" {
missing publishdir

2024-05-22 20:42 UTC, arnaudbore commented on modules/nf-scil/bundle/labelmap/meta.yml
> +      pattern: "*.{nii,nii.gz}"
be more specific

2024-05-22 20:42 UTC, arnaudbore commented on modules/nf-scil/bundle/labelmap/meta.yml
> +      pattern: "*.{nii,nii.gz}"
.nii.gz no need for nii alone

2024-05-22 20:42 UTC, arnaudbore commented on modules/nf-scil/bundle/labelmap/meta.yml
> +  - "@gabknight"
add your name

2024-05-23 11:51 UTC, arnaudbore approved these changes
small comment otherwise LGTM !

2024-05-24 13:22 UTC, arnaudbore approved these changes

2024-05-24 13:22 UTC, merged