[Module] Stats tractometry module.
scilus/nf-scil pull request #160
Opened 2024-05-29 15:10 UTC by ThoumyreStanislas

## Describe your changes

Add bundle/stats module.

## List test packages used by your module

- `tractometry.zip`

## Checklist before requesting a review

- Create the tool:
  - [x] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [x] Add test data locally for tests with the fork repository
  - [x] Generate the test infrastructure and _md5sum_ for all outputs
- Ensure the syntax is correct :
  - [x] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [x] Lint everything. Ensure your variables have good names.

2024-05-30 15:03 UTC, gagnonanthony approved these changes
LGTM! 🍻

2024-06-10 14:23 UTC, AlexVCaron requested changes
Good job 👏🏻 a few comments and this should be good to go !

2024-06-10 14:23 UTC, AlexVCaron commented on modules/nf-scil/bundle/stats/tests/nextflow_light.config
> +
```suggestion
```

2024-06-13 00:45 UTC, AlexVCaron approved these changes
Very good job :+1: LGTM !

2024-06-13 00:46 UTC, AlexVCaron commented on modules/nf-scil/bundle/stats/main.nf
> +        do\
Yeah, it's the sad truth of bash.

2024-06-13 00:47 UTC, merged