[WIP][Module] Freesurfer warp convert
scilus/nf-scil pull request #161
Opened 2024-06-06 18:57 UTC by anroy1

Warp conversion module - designed initially to convert freesurfer registration warp (affine and deform) to ants-itk. Then decided to generalize the module for all cases possible. Receives one affine matrix, one deform warp, source and target images for orientation (and freesurfer licence) and outputs converted affine and deform.

To-do: 
- should it be able to manage receiving only one or the other in input?
- nf-test migration
- integration of more test cases
- integration of test data; right now, only using local data.

2024-06-07 15:15 UTC, AlexVCaron requested changes, later dismissed
blabla dummy comment

2024-06-21 18:11 UTC, AlexVCaron requested changes

2024-06-21 18:11 UTC, AlexVCaron commented on modules/nf-scil/registration/convert/tests/main.nf.test.snap
You're not catching any output files here. Have a check at what the test generates when you run it (in `.nf-test`, you might want to delete the directory first so it is not overcrowded), to be sure the extensions are okay and match the module's output clauses

2024-08-24 16:51 UTC, anroy1 commented on modules/nf-scil/registration/convert/tests/main.nf.test.snap
Added the test data. Some unsolved issues:
1. Convert to FSL is not implemented. We could mark as to be solved later.
2. Assertion of conversion to freesurfer affine format (.lta) doesn't work. I'm looking into it. 

Other than that, it should be ready for a review.

2026-06-12 14:09 UTC, closed without merging