[WIP] Add N4
scilus/nf-scil pull request #4
Opened 2023-11-01 20:54 UTC by arnaudbore

So far so good, didn't test anything yet and feel like we quickly need to come up with a way to handle test data.

2023-11-02 01:59 UTC, AlexVCaron commented
Can you remove the auto-generated TODOs ? I'll do a first pass afterwards, but at first glance the module looks good

2023-11-02 15:35 UTC, arnaudbore commented
> Can you remove the auto-generated TODOs ? I'll do a first pass afterwards, but at first glance the module looks good

Done

2023-11-03 16:02 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/main.nf
> +    tuple val(meta), path("*dwi_n4.nii.gz")            , emit: dwi
Align the emit: clauses for both outputs

2023-11-03 16:06 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
> +  - "ANTs"
Move in the tools section if you want to describe ANTs and scilpy. Else here just put some keywords.

2023-11-03 16:06 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
> +  - "preproc":
Remove "preproc". It is autogenerated based on the category we specify, but we don't want it

2023-11-03 16:06 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
> +  - b0:
missing newline

2023-11-03 16:07 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/meta.yml
> +  - dwi:
missing newline

2023-11-03 16:11 UTC, AlexVCaron requested changes
Minor comments. Can you add dummy lightweight test data so the whole test suite runs for the POC ? I would like to have a working example next thursday with all the modules we made.

We will address a new test data framework then. I intend to play with DVC a little bit, see what we can get from it.

2023-11-04 04:22 UTC, arnaudbore commented
All the comments have been fixed but end up with an error I could not resolve...

2023-11-06 21:08 UTC, AlexVCaron commented on tests/modules/nf-scil/preproc/n4/main.nf
> +        file(params.test_data['preproc']['n4']['b0_mask'], checkIfExists: true)
Bad key : 'dwi', should be 'image'

2023-11-06 21:08 UTC, AlexVCaron commented on tests/modules/nf-scil/preproc/n4/main.nf
> +    input = [
Check the commas between the list's items

2023-11-06 21:09 UTC, AlexVCaron commented on tests/config/test_data.config
> +                image = "${params.test_data_base_n4}/main/.test_data/preproc/dwi.nii.gz"
Replace `main` with the name of your source branch

2023-11-06 21:14 UTC, AlexVCaron commented on tests/modules/nf-scil/preproc/n4/test.yml
> +    - path: "output/preproc/test_dwi_n4.nii.gz"
Did you generate the md5sum yourself ? Nextflow does not like it on my end when running the tests. If yes, just remove it, I will regen all md5sum anyway when we have the true test infra.

2023-11-07 19:13 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/main.nf
> +            N4BiasFieldCorrection: \$(N4BiasFieldCorrection --version 2>&1 | sed -n 's/ANTs Version: \\([0-9.]\\+\\)/\\1/p')
```suggestion
            N4BiasFieldCorrection: \$(N4BiasFieldCorrection --version 2>&1 | sed -n 's/ANTs Version: v\\([0-9.]\\+\\)/\\1/p')
```

2023-11-07 19:13 UTC, AlexVCaron commented on modules/nf-scil/preproc/n4/main.nf
> +        N4BiasFieldCorrection: \$(N4BiasFieldCorrection --version 2>&1 | sed -n 's/ANTs Version: \\([0-9.]\\+\\)/\\1/p')
```suggestion
            N4BiasFieldCorrection: \$(N4BiasFieldCorrection --version 2>&1 | sed -n 's/ANTs Version: v\\([0-9.]\\+\\)/\\1/p')
```

2023-11-07 19:15 UTC, AlexVCaron commented on tests/config/test_data.config
> +                dwi = "${params.test_data_base_n4}/n4_module/.test_data/preproc/dwi.nii.gz"
You can switch back those endpoints to target the `main` branch on `scilus` nf-scil

2023-11-07 19:16 UTC, AlexVCaron requested changes
Last fix to make the version extraction for N4 work. Don't forget to set the test_data endpoint back. Then we can merge !

2023-11-07 19:16 UTC, AlexVCaron requested changes
Last fix to make the version extraction for N4 work. Don't forget to set the test_data endpoint back. Then we can merge !

2023-11-07 20:06 UTC, AlexVCaron approved these changes

2023-11-07 20:07 UTC, merged