Freewater module
scilus/nf-scil pull request #61
Opened 2024-02-08 16:51 UTC by karanphil

## Describe your changes
I added a freewater module! It is really close to the NODDI module.

## Say which test data are used by your module
It uses the commit_amico test data.

## Checklist before requesting a review

- Create the tool:
  - [ ] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [ ] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [ ] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [ ] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [ ] Add test data locally for tests with the fork repository
  - [ ] Generate the test infrastructure and _md5sum_ for all outputs
  - [ ] Test the module in a **REAL** DSL2 pipeline or a _dummy_ one
- Ensure the syntax is correct :
  - [ ] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [ ] Lint everything. Ensure your variables have good names.

2024-02-08 17:10 UTC, gagnonanthony approved these changes
All good! 💯

2024-05-07 19:24 UTC, karanphil commented
I updated the tests for the new reconst/freewater module! Should be ready to re-review @Manonedde @gagnonanthony @arnaudbore

2024-05-09 15:14 UTC, karanphil commented on modules/nf-scil/reconst/freewater/tests/main.nf.test.snap
> +                ],
As discussed, the script only returns kernels since no kernel is given in input.

2024-05-09 15:14 UTC, karanphil commented on modules/nf-scil/reconst/freewater/tests/main.nf.test
> +        }
We don't have kernels in test data sadly.

2024-05-09 19:49 UTC, gagnonanthony approved these changes
All good! 💯

2024-05-14 16:41 UTC, AlexVCaron commented
Update your container to 2.0.2, then LGTM 🚢

2024-05-14 16:42 UTC, AlexVCaron requested changes
Update your container to 2.0.2, then LGTM 🚢

2024-05-14 18:13 UTC, AlexVCaron approved these changes

2024-05-14 18:14 UTC, merged