[WIP} add module Antsbet
scilus/nf-scil pull request #69
Opened 2024-02-08 21:01 UTC by ThoumyreStanislas

add module bet t1 with antsbrainextraction.sh
test passed correctly

2024-02-29 20:37 UTC, ThoumyreStanislas commented
The tests failed because I added new data and tried with a local direction for the data and the test passed. I then changed the directory to nf-scil and the test failed because the data was missing from nf-scil.

2024-03-11 21:15 UTC, AlexVCaron commented
Can you share me the missing test data ? Either in an archive or directly here as links. I'll add them so they are available for your test case using the Scilpy_Fetcher

2024-03-12 16:05 UTC, AlexVCaron commented
The test package is online, the name : `antsbet.zip` !

2024-03-12 19:43 UTC, AlexVCaron requested changes
Some really minor comments. I'll review further once tests are running :wink:

2024-03-12 19:43 UTC, AlexVCaron commented on modules/nf-scil/betcrop/antsbet/main.nf
> +
remove newline

2024-03-12 19:43 UTC, AlexVCaron commented on modules/nf-scil/betcrop/antsbet/main.nf
> +    tuple val(meta), path(t1), path(template), path(map)
Rename `map` to `tissues_probabilities` or something more telling

2024-03-12 19:43 UTC, AlexVCaron commented on modules/nf-scil/betcrop/antsbet/meta.yml
Capitalize `T1` in descriptions this file (don't capitalize variables and symbols)

2024-03-14 13:45 UTC, AlexVCaron commented
The archive is up-to-date on the main branch ! I placed two variations of the `T1`image :

- `t1.nii.gz` which is really close to the template (not the best test case)
- `t1_unaligned.nii.gz` which I virtually moved away further (two rotations and a translation, better as a test)

Can you try recreating the test yml files with the `unaligned` image, see if it passes ?

2024-03-18 17:49 UTC, AlexVCaron approved these changes

2024-03-18 17:50 UTC, merged