[WIP] New module topup
scilus/nf-scil pull request #87
Opened 2024-03-06 03:40 UTC by arnaudbore

## Describe your changes

Add Topup module - Combinaison of prepare_dwi_for_topup and Topup from tractoflow DSL1

## Say which test data are used by your module

## Checklist before requesting a review

- Create the tool:
  - [ ] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [ ] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [ ] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [ ] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [ ] Add test data locally for tests with the fork repository
  - [ ] Generate the test infrastructure and _md5sum_ for all outputs
  - [ ] Test the module in a **REAL** DSL2 pipeline or a _dummy_ one
- Ensure the syntax is correct :
  - [ ] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [ ] Lint everything. Ensure your variables have good names.

2024-03-12 13:01 UTC, ThoumyreStanislas reviewed
LGTM! Well done!

2024-03-12 16:04 UTC, AlexVCaron commented
Test package is up to date !

2024-03-19 17:36 UTC, AlexVCaron requested changes
Very nice job, I have only minor comments, really. Once addressed, I'll just go ahead and merge ! :ship:

2024-03-19 17:36 UTC, AlexVCaron commented on modules/nf-scil/preproc/topup/main.nf
> +    def b0_thr_extract_b0 = task.ext.b0_thr_extract_b0 ? task.ext.b0_thr_extract_b0 : ""
For your knowledge, and if you want to do it here, there is a shorter way to write the ternary operator when the quantities around the `?` are the same, e.g. :

```
    (task.ext.prefix_topup ? task.ext.prefix_topup : "") === (task.ext.prefix_topup ?: "")
```

Just a bit of nice groovy flavour :stuck_out_tongue:

2024-03-19 17:36 UTC, AlexVCaron commented on modules/nf-scil/preproc/topup/main.nf
> +        scilpy: 1.6.0
```suggestion
        scilpy: 1.6.0
        antsRegistration: 2.4.3
        fsl: \$(flirt -version 2>&1 | sed -n 's/FLIRT version \\([0-9.]\\+\\)/\\1/p')
```

2024-03-19 17:36 UTC, AlexVCaron commented on modules/nf-scil/preproc/topup/main.nf
> +        scilpy: 1.6.0
Same comment as above

2024-03-19 17:36 UTC, AlexVCaron commented on modules/nf-scil/preproc/topup/meta.yml
> +      pattern: "*__movpar.txt"
Reoder this to align with the modules output order

2024-03-19 23:28 UTC, AlexVCaron approved these changes

2024-03-19 23:28 UTC, merged